name: Deploy Infrastrucutre

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source code
              uses: actions/checkout@main
        
            - name: Authenticate user
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: "eu-central-1"

            - name: List buckets
              run: |
                aws s3 ls
